### ISSUE TITLE
Your code showing error

### ISSUE THREAD

**Issue by shrikant2233** [redianmarku/MesoOn#3]
I will attach the photo of the error hope u overcome this error.
![sss](https://user-images.githubusercontent.com/44123823/87876954-04099d00-c9f9-11ea-81d9-eed02634a67b.png)

**Comment by redianmarku** [comment]
You need to run on terminal:
1- python manage.py makemigrations
2- python manage.py migrate
3- python manage.py runserver

**Comment by MUDASSARHASHMI** [comment]
@redianmarku Just delete all migrations and db from your code and run 1. makemigrations 2. migrate 3. runserver. Make sure to completely delete all migrations files. Cheers
